### ISSUE TITLE
안녕하세요! daum_postcode_search를 사용하고 있는 개발자입니다.

### ISSUE THREAD

**Issue by chugue** [zerodice0/BlackBearsFlutterLibrary#1]
덕분에 daum_postcode_search 라이브러리를 잘 사용하고 있었는데요. 

최근에 xcode가 업데이트 되면서 flutter_inappview를 버전을 최신화 하지 않으면, ios빌드 과정에서 아래와 같은 에러가 발생하는 데요. 

![image](https://github.com/user-attachments/assets/0388b0ad-ba74-478f-bd76-4348f35d0a37)

현재 daum_postcode_search 라이브러리가 flutter_inappview: 5.8.0까지만 호환이 되어서, 혹시 어떻게 해결할 방법이 없을까 문의를 남기게 되었습니다.

**Comment by zerodice0** [comment]
아무도 사용하지 않는 줄 알고 오랜시간 손을 놨었는데, 확인해보니 너무 오랫동안 손을 놓고 있어서 마이그레이션하는데 시간이 좀 걸릴 것 같네요. 확인해보고 마이그레이션해보도록 하겠습니다. :)

**Comment by chugue** [comment]
답변 감사합니다!

**Comment by zerodice0** [comment]
수정된 사항이 포함하여, 0.0.3버전이 배포됐습니다. :)

**Comment by chugue** [comment]
우와 정말 감사합니다. 최고에요!
